name: Pipeline Base 5 Fases

on:
  push:

jobs:

  Preparacion:
    runs-on: ubuntu-latest
    steps:
      - name: Preparando entorno
        run: echo "Configurando entorno..." && sleep 3

  Compilacion:
    needs: Preparacion
    runs-on: ubuntu-latest
    steps:
      - name: Compilando proyecto
        run: echo "Compilando codigo..." && sleep 4

  Pruebas:
    needs: Compilacion
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutando pruebas
        run: echo "Validando sistema..." && sleep 5

  Validacion_Final:
    needs: Pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Verificando calidad
        run: echo "Revisando calidad del build..." && sleep 3

  Despliegue:
    needs: Validacion_Final
    runs-on: ubuntu-latest
    steps:
      - name: Desplegando sistema
        run: echo "Sistema desplegado exitosamente." && sleep 3
