name: Pipeline CPU 5 Etapas

on:
  push:

jobs:

  IF:
    runs-on: ubuntu-latest
    steps:
      - name: Instruction Fetch
        run: echo "Buscando instruccion en memoria..." && sleep 3

  ID:
    needs: IF
    runs-on: ubuntu-latest
    steps:
      - name: Instruction Decode
        run: echo "Decodificando instruccion..." && sleep 3

  EX:
    needs: ID
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        run: echo "Ejecutando operacion en ALU..." && sleep 3

  MEM:
    needs: EX
    runs-on: ubuntu-latest
    steps:
      - name: Memory Access
        run: echo "Accediendo a memoria..." && sleep 3

  WB:
    needs: MEM
    runs-on: ubuntu-latest
    steps:
      - name: Write Back
        run: echo "Escribiendo resultado en registro." && sleep 3
